spring:
  application:
      name: su-ai-code
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yukina.suaicode.controller
knife4j:
  enable: true
  setting:
    language: zh_cn